# application-dev.yml
multitenant:
  require-api-key: true
  strategy: collection-per-tenant
  base-database: logs_system
  log-collection: log_events
  ensure-indexes: true
  dev:
    fallback-tenant-id: ""      
