spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/logs_system
  data.mongodb.auto-index-creation: true

multitenant:
  strategy: collection-per-tenant
  base-database: logs_system
  log-collection: log_events
  ensure-indexes: true
  require-api-key: true

security:
  basic:
    enabled: false
  catalogs:
    protect-writes: false
