spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.2
          max-tokens: 700
  data:
    mongodb:
      uri: mongodb://localhost:27017/logs_system
      auto-index-creation: true
  jackson:
    parser:
      allow-comments: true

multitenant:
  strategy: single
  base-database: logs_system
  log-collection: log_events
  ensure-indexes: true
  require-api-key: true

security:
  basic:
    enabled: false
  catalogs:
    protect-writes: false
  jwt:
    secret: "change-me-very-long-secret-key-32-bytes-min-1234567890"
    issuer: "backlogs"
    ttl-minutes: 120
  self-signup:
    enabled: false

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

biometric:
  dif-fp: ./data/fp
  dir-face: ./data/face
  threshold: 25

backlogs:
  rate-limit:
    enabled: true

    # ------------- BUCKET POR API-KEY ---------------
    api-key:
      capacity: 400                             # (burst 2s)
      refill-tokens: 200                        # (200 logs/seg promedio por Api Key)
      refill-seconds: 1

    # ------------ BUCKET POR TENANT ----------------
    tenant:
      capacity: 4000                          # (burst 2s)
      refill-tokens: 2000                     # (2000 logs/seg promedio por tenant)
      refill-seconds: 1

    # ------------ CACHE (EVICTION / TTL) ----------
    cache:
      ttl-minutes: 60       # se borra si no se usa en 30 min
      max-size: 300000      # limite duro de buckets en memoria

springdoc:
  swagger-ui:
    # UX
    doc-expansion: none
    filter: true
    try-it-out-enabled: true
    display-request-duration: true
    persist-authorization: true
    operations-sorter: alpha
    tags-sorter: alpha

    # Ocultar el bloque "Schemas" por defecto (se ve más limpio)
    default-models-expand-depth: -1
    default-model-expand-depth: 2

    # Grupos (para que se vean "bonitos" en el dropdown y por orden)
    urls:
      - name: 01 - Admin
        url: /v3/api-docs/01%20-%20Admin
      - name: 02 - Core
        url: /v3/api-docs/02%20-%20Core
      - name: 03 - Public
        url: /v3/api-docs/03%20-%20Public
    urls-primary-name: 01 - Admin

server:
  address: 0.0.0.0
  port: 8080

