# Configuración para la base de datos MySQL (Desarrollo)


# Se esta utilizando la URI
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/logs_system}

security.jwt.refresh-ttl-minutes=120




