spring.application.name=backlogs
spring.profiles.active=mail

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=soporte.tecnico@grupo-santoro.com.mx
spring.mail.password=wnnkjroexgypcpss

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.enable=false
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

app.mail.from=soporte.tecnico@grupo-santoro.com.mx
app.mail.from-name=Backlogs Santoro

eva.openai.api-key=${EVA_OPENAI_API_KEY:}
#spring.profiles.active=dev

multitenant.require-api-key=true
multitenant.legacy-tenant-filter-enabled=false
multitenant.header.tenant=X-Tenant

security.jwt.secret=KoSd8fKjYA1Bdy8nFHAYZlcAhj9bCIGQGGrhKPAMmGo=
security.jwt.issuer=backlogs
security.jwt.ttl-minutes=120

server.error.include-message=always
server.error.include-binding-errors=always
spring.mvc.log-request-details=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
# Esto ayuda si tienes rutas muy complejas
springdoc.show-actuator=true
springdoc.model-and-view-resolved-as-json=true